# Setup
title: Zea's Diaries
tagline:
url: https://zea17.github.io/
paginate: 1
baseurl: ""
permalink: pretty


# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Zea Akbari
  url: https://zea17.github.io/
  email: zeaak17@gmail.com

# Custom vars
version: 3.0.0

paginate_path: "/blog/page:num/"
paginate: 5
plugins:
  - jekyll-paginate